### ISSUE TITLE
repo-add does not behave the same as Arch's version

### ISSUE THREAD

**Issue by joaodefelipe** [CachyOS/pacman#2]
Hello! I've noticed an inconsistency in how repo-{add,remove} behaves.

It is my understanding that when `--` occurs in the command line, all arguments after it are to be treated as positional arguments.
However, before `--`, it's expected a flag might occur anywhere — even mixed with positional arguments.

I caught this behavior because I use [Paru](https://github.com/Morganamilo/paru), and with the `SignDb` option enabled, it puts the `-s` flag after all the positional arguments — maybe not ideal, but not incorrect usage either.

Reproduction: `repo-add SOME_DB SOME_PACKAGE -s` works with Arch's `repo-add`, but not with CachyOS's.

#1 seems to fix this, but there's likely some edge case I haven't thought of. Please, do tell if that's the case.

**Comment by vnepogodin** [comment]
That isn't correct behavior for original `repo-add` either. `repo-add` expects in that order:
<options/flags> <path to db> <packages>

**Comment by joaodefelipe** [comment]
Following the man page and help message, what you said does make sense.

So, accepting options/flags after positional arguments is a bug in the original `repo-add`, and passing a flag after positional arguments is a bug in Paru... I guess the latter can (and should) be fixed easily enough, but I'm not sure if there are more tools out there doing the same.

Depending on how long ago this bug got introduced in Arch's `repo-add`, I don't think it's a bad idea to provide a drop-in replacement, and warn about incorrect usage — ultimately, it's up to you.

**Comment by vnepogodin** [comment]
> Following the man page and help message, what you said does make sense.
> 
> So, accepting options/flags after positional arguments is a bug in the original `repo-add`, and passing a flag after positional arguments is a bug in Paru... I guess the latter can (and should) be fixed easily enough, but I'm not sure if there are more tools out there doing the same.
> 
> Depending on how long ago this bug got introduced in Arch's `repo-add`, I don't think it's a bad idea to provide a drop-in replacement, and warn about incorrect usage — ultimately, it's up to you.

actually keep in mind that `repo-add` from archlinux core repo doesn't support `--` flag at all. the new version of pacman will provide it, but its expected to release quite soon.
so maybe paru will break when they will release, maybe not.

I also think that original `repo-add` has a bug with `-s` after positional arguments. implementation of `--` in original `repo-add` works equally as I implemented -> it does break out of loop if it reaches `--`. ref https://gitlab.archlinux.org/pacman/pacman/-/blob/master/scripts/repo-add.sh.in?ref_type=heads#L644

**Comment by vnepogodin** [comment]
I can remove `--`. that should fix it, but paru will much probably be broken then anyways

**Comment by joaodefelipe** [comment]
> I also think that original `repo-add` has a bug with `-s` after positional arguments. implementation of `--` in original `repo-add` works equally as I implemented -> it does break out of loop if it reaches `--`. ref https://gitlab.archlinux.org/pacman/pacman/-/blob/master/scripts/repo-add.sh.in?ref_type=heads#L644

#1 also breaks out of the loop in that case.

> I can remove --. that should fix it, but paru will much probably be broken then anyways

#1 works with current Paru (or a possible future Paru that uses `--`). This is because arguments before `--` that don't match flags or options are treated as positional arguments.

| command | meaning |
| -- | -- |
| `repo-add mydb mypkg -s` | add package `mypkg` to database `mydb`; sign the database (this is what Paru does) |
| `repo-add mydb mypkg -s -k foo` | add package `mypkg` to database `mydb`; sign the database with key `foo` |
| `repo-add mydb mypkg -- -s` | add packages `mypkg` and `-s` to database `mydb` |
| `repo-add -s -- -s -k` | add package `-k` to database `-s`; sign the database |

**Comment by vnepogodin** [comment]
fixed in https://github.com/CachyOS/pacman/pull/1
